require "Constant"
require "FirebaseDefault"
require "class.Toat"
require "Tab.Tab"
require "Tab.TabManager"

require "Shop.ShopManager"
require "Shop.ShopBuyFishManager"
require "Shop.ShopDecorationManager"
require "Shop.Item.FishAnim"
require "Shop.Item.FishItem"
require "Shop.Item.DecorationItem"
require "Shop.Item.StallItem"
require "Shop.Item.EventItem"
require "Shop.Item.BlockItem"
require "Shop.ShopStallManager"

require "Shop.PaymentMethod"

require "DataManager"

require "Bag.BagManager"
require "Bag.BagFriendManager"
require "Bag.BagItem"
require "Bag.DetailItem"

require "Decor.DecorItem"
require "Decor.DecorManager"
require "Decor.PlaceManager"
require "Decor.PlaceItem"

require "Mail.MailPrefab"

require "Chat.ChatManager"
require "Chat.ChatItem"
require "Chat.ChatTopbar"

require "Player.PlayerInfomation"
require "Player.PlayerManager"
require "Player.getCoinExp"
require "Player.CreateUser"
require "Player.NextLevel"

require "Fish.FishManager"
require "Fish.Fish"
require "Fish.GetFishManager"
require "Fish.FishStatus"
require "Fish.MoveToTarget"
require "Fish.FishThinking"
require "DropItem.DropUpList"
require "DropItem.TextAmount"
require "StringFormat"
require "Popup.Popup_demo"
require "Popup.Popup_informNormal"
require "Popup.PopupAnimationTest"
require "Popup.PopupSetting"
require "Popup.PopupMail"
require "Popup.PopupMailDetail"
require "Popup.PopupLevelUp"
require "Popup.PopupChat"
require "Popup.PopupCreateUser"
require "Popup.PopupDialog"
require "Popup.Popup_breed"
require "Popup.PopupReward"
require "Popup.PopupProfile"
require "Popup.PopupPurchase"
require "Popup.PopupInfoFriend"
require "Popup.Popup_SellFish"
require "Popup.PopupExchange"
require "Popup.PopupBag"
require "Popup.PopupBagFriend"
require "Popup.PopupBuyAmount"
require "Popup.PopupRanking"

require "class.Enum"
require "class.MasterSocket"
require "class.Player"
require "class.Aquarium"
require "class.PlayerSocket"
require "class.Me"
require "class.FishMaster"
require "class.DecoMaster"
require "class.Item"
require "class.ItemSocket"
require "class.ShopSocket"
require "class.ShopFish"
require "class.ShopDecoration"
require "class.ShopStall"
require "class.Fish1"
require "class.FishSocket"
require "class.AquariumSocket"
require "class.Bag.BagSocket"
require "class.Bag._BagDecoration"
require "class.Bag._BagItem"
require "class.Decor._DecorItem"
require "class.Mail"
require "class.MailSocket"
require "class.Chat"
require "class.ChatSocket"
require "class.ProfileSocket"
require "class.FriendSocket"
require "class.Friend"
require "class.FriendManager"
require "class.CurrencySocket"
require "class.RankingSocket"
require "Mail.MailItemPrefab"
require "Mail.MailManager"
require "class.QuestsSocket"
require "class.Quests"

require "Menu.MenuManager"
require "Menu.MenuPagination"
require "Menu.MenuButton.MenuButtonBase"
require "Menu.MenuButton.MenuBtnBag"
require "Menu.MenuButton.MenuBtnBagFriend"
require "Menu.MenuButton.MenuBtnBreed"
require "Menu.MenuButton.MenuBtnCursor"
require "Menu.MenuButton.MenuBtnDecor"
require "Menu.MenuButton.MenuBtnFood"
require "Menu.MenuButton.MenuBtnFriend"
require "Menu.MenuButton.MenuBtnMail"
require "Menu.MenuButton.MenuBtnRacket"
require "Menu.MenuButton.MenuBtnShop"
require "Menu.MenuButton.MenuBtnPhoto"
require "Menu.MenuButton.MenuBtnRanking"
require "Menu.MenuButton.MenuBtnMission"

require "Menu.ToolBar"
require "Friend.FriendListManager"
require "Friend.LookingFriend"
require "Friend.FriendItem"
require "Friend.FriendLogItem"
require "Friend.FriendLogManager"
require "Friend.FriendVisitManager"
require "Friend.BackFriendZone"
require "Friend.FriendRequestItem"
require "Friend.FriendRequestManager"
require "Friend.NoticationNewFriend"
require "Friend.FriendCheckOnline"

require "ParticleManager"

require "Food.FoodManager"
require "Food.FoodFriendManager"
require "Food.FoodItem"

require "StateMachine.StateTest"

require "StateMachine.SettingState.SettingManager"
require "StateMachine.SettingState.StateOpenPoupSetting"
require "StateMachine.SettingState.StateHidePopupSetting"
require "StateMachine.SettingState.StateLogout"
-- require "Toolbar.Toolbar"

require "DropItem.DropUpManager"
require "DropItem.DropUpFriendManager"
require "DropItem.ItemFlyUp"
require "DropItem.ItemFlyUpFriend"
require "Audio.AudioManager"
require "Aquarium.AquariumManager"
require "Aquarium.AquariumFriendManager"
require "Aquarium.AquariumItem"
require "Aquarium.AquariumList"
require "Aquarium.AquariumBonus"
require "UI.CanvasManager"

require "Energy.EnergyManager"

require "Helper.BarHelper"
require "Helper.GetPositionHelper"

require "Animation.ScaleAnimation"
require "Animation.TextRunAnimation"

require "class.BreedSocket"
require "Breed.BreedFishSelectItem"
require "Breed.BreedItemMaterial"
require "Breed.BreedSelectMaterial"

require "Quests.QuestsItem"
require "Quests.QuestsManager"

require "FirstLoad"

require "Purchase.ExchangeItem"

require "Photo.PhotoManager"


require "Test2"
require "TestSocket"

require "Ranking.RankingItem"
require "Ranking.RankingTab"

require "Quests.QuestsManager"
